import { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
    // ---- push
    {
        id: "pushup",
        name: "Push-up",
        region: "push",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Ribs down, elbows tracking back at 45°.",
    },
    {
        id: "incline-pushup",
        name: "Incline push-up",
        region: "push",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Hands on a chair or counter. Slow on the way down.",
    },
    {
        id: "tempo-pushup",
        name: "Tempo push-up",
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Three seconds down, one second up, no pause at the bottom.",
    },
    {
        id: "pike-pushup",
        name: "Pike push-up",
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hips high, crown of the head toward the floor.",
    },
    {
        id: "dips-chair",
        name: "Bench dip",
        region: "push",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Shoulders down, only go as deep as feels clean.",
    },
    {
        id: "db-press",
        name: "Dumbbell floor press",
        region: "push",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Press slightly toward your feet, not straight over the face.",
    },
    {
        id: "db-overhead",
        name: "Dumbbell overhead press",
        region: "push",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Squeeze glutes so the ribs stay stacked.",
    },
    {
        id: "band-press",
        name: "Band chest press",
        region: "push",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor behind you at chest height. Control the return.",
    },

    // ---- pull
    {
        id: "band-row",
        name: "Band row",
        region: "pull",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Lead with the elbow, pause one second at the chest.",
    },
    {
        id: "band-pulldown",
        name: "Band pulldown",
        region: "pull",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor high. Pull the elbows into your back pockets.",
    },
    {
        id: "db-row",
        name: "Dumbbell single-arm row",
        region: "pull",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Flat back, no twisting to finish the rep.",
    },
    {
        id: "db-pullover",
        name: "Dumbbell pullover",
        region: "pull",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Arms nearly straight, stop where the ribs want to flare.",
    },
    {
        id: "pullup",
        name: "Pull-up",
        region: "pull",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 2,
        unit: "reps",
        cue: "Start from a dead hang, chest to bar.",
    },
    {
        id: "chinup-negative",
        name: "Chin-up negative",
        region: "pull",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Jump to the top, lower for five seconds.",
    },
    {
        id: "bar-hang",
        name: "Active bar hang",
        region: "pull",
        equipment: "pullupbar",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Pull the shoulders away from the ears and hold.",
    },
    {
        id: "table-row",
        name: "Table / towel row",
        region: "pull",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Body in one line, heels dug in.",
    },
    {
        id: "prone-swimmer",
        name: "Prone swimmer",
        region: "pull",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Face down, sweep the arms wide and slow.",
    },

    // ---- legs
    {
        id: "squat",
        name: "Bodyweight squat",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Knees travel over the toes, chest tall.",
    },
    {
        id: "split-squat",
        name: "Split squat",
        region: "legs",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Back knee straight down. Same count on both sides.",
    },
    {
        id: "reverse-lunge",
        name: "Reverse lunge",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Step back softly, push the floor away with the front foot.",
    },
    {
        id: "glute-bridge",
        name: "Glute bridge",
        region: "legs",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Ribs down, squeeze for a full second at the top.",
    },
    {
        id: "single-leg-rdl",
        name: "Single-leg RDL",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Hips square, reach the back heel to the wall.",
    },
    {
        id: "wall-sit",
        name: "Wall sit",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Thighs parallel, breathe through it.",
    },
    {
        id: "calf-raise",
        name: "Slow calf raise",
        region: "legs",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Full height, three-second lower.",
    },
    {
        id: "db-goblet-squat",
        name: "Goblet squat",
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 0,
        unit: "reps",
        cue: "Elbows inside the knees at the bottom.",
    },
    {
        id: "db-rdl",
        name: "Dumbbell RDL",
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hinge at the hip, weight close to the legs.",
    },
    {
        id: "band-abduction",
        name: "Band lateral walk",
        region: "legs",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Band above the knees, small controlled steps.",
    },

    // ---- core
    {
        id: "plank",
        name: "Front plank",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Push the floor away, tuck the tailbone slightly.",
    },
    {
        id: "side-plank",
        name: "Side plank",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Stack the shoulders, lift the bottom ribs.",
    },
    {
        id: "deadbug",
        name: "Dead bug",
        region: "core",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Low back stays glued to the floor.",
    },
    {
        id: "hollow-hold",
        name: "Hollow hold",
        region: "core",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Lower the legs until the back wants to arch, then stop.",
    },
    {
        id: "leg-raise",
        name: "Lying leg raise",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Control the descent, no swinging.",
    },
    {
        id: "bird-dog",
        name: "Bird dog",
        region: "core",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Long, slow reach. Hips level the whole time.",
    },
    {
        id: "hanging-knee-raise",
        name: "Hanging knee raise",
        region: "core",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 2,
        unit: "reps",
        cue: "Curl the pelvis, don't just lift the thighs.",
    },
    {
        id: "db-suitcase-hold",
        name: "Suitcase carry hold",
        region: "core",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "One weight, stay perfectly level.",
    },

    // ---- mobility
    {
        id: "worlds-greatest",
        name: "World's greatest stretch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Lunge, rotate, breathe out at the end range.",
    },
    {
        id: "cat-cow",
        name: "Cat-cow",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Move one vertebra at a time.",
    },
    {
        id: "hip-90-90",
        name: "90/90 hip switch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Sit tall, switch without using the hands.",
    },
    {
        id: "thoracic-rotation",
        name: "Open book rotation",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Follow your hand with your eyes.",
    },
    {
        id: "couch-stretch",
        name: "Couch stretch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Tuck the pelvis before leaning back.",
    },
    {
        id: "deep-squat-hold",
        name: "Deep squat hold",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Elbows to knees, heels down if you can.",
    },
    {
        id: "shoulder-dislocate",
        name: "Band shoulder pass-through",
        region: "mobility",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Wide grip, slow arc, no shrugging.",
    },
    {
        id: "ankle-rock",
        name: "Half-kneel ankle rock",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Knee past the toes, heel stays down.",
    },

    // ---- cardio / conditioning
    {
        id: "jump-rope",
        name: "Rope skips (or mimic)",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Small hops, quiet landings.",
    },
    {
        id: "mountain-climber",
        name: "Mountain climber",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Hips low, fast feet.",
    },
    {
        id: "step-up",
        name: "Fast step-up",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Full foot on the step, drive through the hip.",
    },
    {
        id: "burpee",
        name: "Burpee",
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Chest to floor, stand tall to finish.",
    },
    {
        id: "shadow-box",
        name: "Shadow boxing",
        region: "cardio",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Stay light on the feet, breathe on every punch.",
    },
    {
        id: "squat-jump",
        name: "Squat jump",
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Land soft and absorb into the next rep.",
    },
];

export const EXERCISE_BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));
