import { Exercise } from "./types";

/**
 * Entries marked "fallback" reuse a similar movement because no exact
 * animation exists. Several exercises can share one imageName, which is
 * why ids are kept stable instead of being renamed to match.
 */
export const EXERCISES: Exercise[] = [
    // ---- push
    {
        id: "pushup",
        name: "Push-up",
        imageName: "push-up",
        region: "push",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Start in a straight plank with hands just outside shoulder width. Brace your core and lower your chest with elbows about 45° from your body. Keep hips level, then press the floor away to return.",
    },
    {
        id: "incline-pushup",
        name: "Incline push-up",
        imageName: "incline-push-up",
        region: "push",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Place hands on a stable chair or counter and step back into a straight line. Brace your core, lower your chest toward the surface with elbows at about 45°, then press back up without letting hips sag.",
    },
    {
        id: "tempo-pushup",
        name: "Tempo push-up",
        imageName: "push-up", // fallback
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Set up in a strong plank with hands under or slightly outside shoulders. Lower your body for 3 seconds, keeping elbows around 45°. Press up smoothly for 1 second without pausing at the bottom.",
    },
    {
        id: "pike-pushup",
        name: "Pike push-up",
        imageName: "pike-push-up",
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Start with hands shoulder-width apart and hips raised high into an inverted V. Bend your elbows and lower the crown of your head toward the floor. Keep hips high, then press back to the start.",
    },
    {
        id: "dips-chair",
        name: "Bench dip",
        imageName: "bench-dip",
        region: "push",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Place hands behind you on a stable bench or chair, fingers forward. Keep shoulders down and lower your body by bending the elbows. Stop before shoulder discomfort, then press through your hands to rise.",
    },
    {
        id: "db-press",
        name: "Dumbbell floor press",
        imageName: "dumbbell-bench-press",
        region: "push",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your back with knees bent and a dumbbell in each hand. Start with elbows near the floor, press the weights upward and slightly toward your feet. Lower under control until upper arms gently touch the floor.",
    },
    {
        id: "db-overhead",
        name: "Dumbbell overhead press",
        imageName: "standing-dumbbell-press",
        region: "push",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Stand tall with dumbbells at shoulder height. Brace your core and squeeze your glutes to keep ribs stacked over your pelvis. Press the weights overhead without leaning back, then lower them under control.",
    },
    {
        id: "band-press",
        name: "Band chest press",
        imageName: "dumbbell-bench-press", // fallback
        region: "push",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band behind you at chest height and hold the handles near your chest. Step forward for tension, brace your core, then press both hands forward. Slowly return without letting the band pull you back.",
    },
    {
        id: "diamond-pushup",
        name: "Diamond push-up",
        imageName: "diamond-push-up",
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Set hands close together under your chest with thumbs and index fingers touching. Keep your body straight, brace your core, and lower with elbows close to your sides. Press the floor away to return.",
    },
    {
        id: "db-lateral-raise",
        name: "Dumbbell lateral raise",
        imageName: "lateral-raise",
        region: "push",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Stand tall with dumbbells at your sides and a slight bend in the elbows. Raise your arms outward until roughly shoulder height, leading with the elbows. Keep shoulders relaxed and lower slowly without swinging.",
    },
    {
        id: "band-overhead-press",
        name: "Band overhead press",
        imageName: "overhead-press", // fallback
        region: "push",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Stand on the middle of the band and hold the handles at shoulder height. Brace your core and squeeze your glutes. Press straight overhead without arching your lower back, then lower with control.",
    },
    // new
    {
        id: "wide-pushup",
        name: "Wide push-up",
        imageName: "push-up", // fallback
        region: "push",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Set hands wider than shoulder width in a straight plank. Brace your core and lower your chest between your hands, keeping elbows at about 45° to 60°. Press the floor away to return without letting hips sag.",
    },
    {
        id: "decline-pushup",
        name: "Decline push-up",
        imageName: "push-up", // fallback
        region: "push",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Place your feet on a stable chair or step with hands on the floor under your shoulders. Brace your core and lower your chest with elbows about 45°. Press back up while keeping your body in one straight line.",
    },
    {
        id: "band-lateral-raise",
        name: "Band lateral raise",
        imageName: "lateral-raise", // fallback
        region: "push",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Stand on the band and hold the handles at your sides with a slight elbow bend. Raise your arms outward to shoulder height, leading with the elbows. Keep shoulders relaxed and lower slowly against the tension.",
    },

    // ---- pull
    {
        id: "band-row",
        name: "Band row",
        imageName: "banded-row",
        region: "pull",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band securely in front of you around chest height. Hold the handles with arms extended, brace your core, and pull elbows back toward your ribs. Pause briefly as the shoulder blades squeeze, then return slowly.",
    },
    {
        id: "band-pulldown",
        name: "Band pulldown",
        imageName: "banded-lat-pulldown",
        region: "pull",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band high overhead and grip the handles. Start with arms extended, brace your core, then pull elbows down toward your back pockets. Squeeze your upper back, then slowly return to full extension.",
    },
    {
        id: "db-row",
        name: "Dumbbell single-arm row",
        imageName: "one-arm-dumbbell-row",
        region: "pull",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Support one hand and knee on a stable surface with your back flat. Hold the dumbbell in the opposite hand. Pull your elbow toward your hip without twisting your torso, pause, then lower the weight slowly.",
    },
    {
        id: "db-pullover",
        name: "Dumbbell pullover",
        imageName: "straight-arm-pulldown", // fallback
        region: "pull",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Lie on your back holding one dumbbell above your chest with arms nearly straight. Slowly lower the weight behind your head while keeping ribs down. Stop before your back arches, then pull the weight back over your chest.",
    },
    {
        id: "pullup",
        name: "Pull-up",
        imageName: "pull-up",
        region: "pull",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 2,
        unit: "reps",
        cue: "Hang from the bar with a controlled grip and arms extended. Brace your core, pull your shoulders down, then drive elbows toward your ribs as you raise your chest toward the bar. Lower slowly to a full hang.",
    },
    {
        id: "chinup-negative",
        name: "Chin-up negative",
        imageName: "negative-pull-up",
        region: "pull",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Use a step or small jump to begin with your chin above the bar. Brace your core and slowly lower yourself for about 5 seconds until your arms are straight. Reset and repeat without dropping quickly.",
    },
    {
        id: "bar-hang",
        name: "Active bar hang",
        imageName: "dead-hang",
        region: "pull",
        equipment: "pullupbar",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Hang from the bar with arms straight and hands secure. Instead of relaxing completely, pull your shoulders down away from your ears and slightly engage your upper back. Hold the position while breathing steadily.",
    },
    {
        id: "table-row",
        name: "Table / towel row",
        imageName: "inverted-row",
        region: "pull",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Use a sturdy table or securely anchored towel. Grip firmly and lean back with your body in one straight line. Drive your elbows back to pull your chest toward your hands, then lower under control.",
    },
    {
        id: "prone-swimmer",
        name: "Prone swimmer",
        imageName: "reverse-snow-angel", // fallback
        region: "pull",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Lie face down with arms extended overhead. Lift them slightly and slowly sweep them outward, down, and toward your sides before returning overhead. Keep movements controlled and avoid shrugging your shoulders.",
    },
    {
        id: "band-facepull",
        name: "Band face pull",
        imageName: "banded-face-pull",
        region: "pull",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band around face height and hold both ends. Pull toward your eyes or forehead while driving elbows outward. At the end, rotate your hands back slightly and squeeze your upper back before returning.",
    },
    {
        id: "db-renegade-row",
        name: "Renegade row",
        imageName: "dumbbell-bent-over-row", // fallback
        region: "pull",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Start in a strong plank holding dumbbells, using a wide stance for stability. Brace your core and row one dumbbell toward your ribs without rotating your hips. Lower it carefully, then alternate sides.",
    },
    {
        id: "chinup",
        name: "Chin-up",
        imageName: "pull-up", // fallback
        region: "pull",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 2,
        unit: "reps",
        cue: "Grip the bar with palms facing you and hands about shoulder width. Start from a controlled hang, brace your core, and pull your elbows down toward your ribs until your chin clears the bar. Lower slowly.",
    },
    // new
    {
        id: "db-bent-row",
        name: "Dumbbell bent-over row",
        imageName: "dumbbell-bent-over-row",
        region: "pull",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hinge at the hips with a flat back and dumbbells hanging below your shoulders. Brace your core and pull both elbows toward your hips. Squeeze your upper back briefly, then lower with control.",
    },
    {
        id: "band-pull-apart",
        name: "Band pull-apart",
        imageName: "banded-face-pull", // fallback
        region: "pull",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Hold a band in front of you at chest height with arms straight. Brace your core and pull your hands apart by squeezing your shoulder blades together. Return slowly without shrugging.",
    },
    {
        id: "band-single-arm-row",
        name: "Band single-arm row",
        imageName: "banded-row", // fallback
        region: "pull",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band in front of you at waist height and hold one handle. Stand tall, brace your core, and pull your elbow back toward your hip without twisting. Pause, then return slowly. Complete both sides.",
    },

    // ---- legs
    {
        id: "squat",
        name: "Bodyweight squat",
        imageName: "bodyweight-squat",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Stand with feet around shoulder width and toes slightly turned out. Brace your core, push hips back, and bend your knees while keeping your chest tall. Lower comfortably, then drive through your whole foot to stand.",
    },
    {
        id: "split-squat",
        name: "Split squat",
        imageName: "split-squat",
        region: "legs",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Take a staggered stance with one foot forward and one behind. Keep your torso upright, lower the back knee straight toward the floor, then drive through the front foot to stand. Complete the same reps on both sides.",
    },
    {
        id: "reverse-lunge",
        name: "Reverse lunge",
        imageName: "reverse-lunge",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Stand tall with feet together. Step one foot backward and lower until both knees bend comfortably. Keep most of your weight through the front foot, then push the floor away to return. Alternate or complete one side at a time.",
    },
    {
        id: "glute-bridge",
        name: "Glute bridge",
        imageName: "glute-bridge",
        region: "legs",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your back with knees bent and feet flat. Brace your core and press through your heels to lift your hips. Keep ribs down and squeeze your glutes for 1 second at the top, then lower slowly.",
    },
    {
        id: "single-leg-rdl",
        name: "Single-leg RDL",
        imageName: "single-leg-romanian-deadlift",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Stand on one leg with a soft knee. Hinge at the hips while extending the other leg behind you. Keep your hips square to the floor and reach the back heel toward the wall. Return by driving the standing foot down.",
    },
    {
        id: "wall-sit",
        name: "Wall sit",
        imageName: "wall-sit",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Place your back against a wall and slide down until your thighs are roughly parallel to the floor. Keep feet flat, knees tracking over toes, and your back supported. Hold the position and breathe steadily.",
    },
    {
        id: "calf-raise",
        name: "Slow calf raise",
        imageName: "calf-raise",
        region: "legs",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Stand tall with feet hip width apart and use support if needed. Rise onto the balls of your feet as high as possible, pause briefly, then lower your heels for a controlled 3-second descent.",
    },
    {
        id: "db-goblet-squat",
        name: "Goblet squat",
        imageName: "goblet-squat",
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 0,
        unit: "reps",
        cue: "Hold one dumbbell vertically against your chest. Stand with feet shoulder width, brace your core, and squat down while keeping your chest tall. Aim to bring elbows inside the knees at the bottom, then stand.",
    },
    {
        id: "db-rdl",
        name: "Dumbbell RDL",
        imageName: "romanian-deadlift",
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hold dumbbells in front of your thighs with a soft knee bend. Push your hips backward while keeping your back neutral and weights close to your legs. Feel the hamstrings stretch, then drive hips forward to stand.",
    },
    {
        id: "band-abduction",
        name: "Band lateral walk",
        imageName: "banded-lateral-walk",
        region: "legs",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Place the band above your knees and bend slightly at the hips and knees. Keep tension on the band as you take small controlled steps sideways. Keep toes forward and avoid letting the knees collapse inward.",
    },
    {
        id: "bulgarian-split-squat",
        name: "Bulgarian split squat",
        imageName: "bulgarian-split-squat",
        region: "legs",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Place your rear foot on a stable elevated surface and position the front foot far enough forward to squat comfortably. Lower the back knee toward the floor while staying controlled, then drive through the front foot to rise.",
    },
    {
        id: "cossack-squat",
        name: "Cossack squat",
        imageName: "cossack-squat",
        region: "legs",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Stand wide with toes slightly turned out. Shift your weight onto one leg and bend that knee while the opposite leg stays extended. Keep the working heel grounded and chest lifted, then push back to center.",
    },
    {
        id: "db-lunge",
        name: "Dumbbell walking lunge",
        imageName: "walking-lunge",
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hold dumbbells at your sides and stand tall. Step forward under control, lower until both knees bend comfortably, then push through the front foot into the next step. Keep your torso slightly hinged and knees aligned.",
    },
    {
        id: "single-leg-bridge",
        name: "Single-leg glute bridge",
        imageName: "single-leg-glute-bridge",
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your back with one foot planted and the other leg extended. Brace your core, drive through the planted heel, and lift your hips while keeping them level. Squeeze the glute at the top, then lower slowly.",
    },
    // new
    {
        id: "lateral-lunge",
        name: "Lateral lunge",
        imageName: "cossack-squat", // fallback
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Stand tall with feet together. Step wide to one side, push your hips back, and bend that knee while the other leg stays straight. Keep your chest lifted and heel down, then push back to the start.",
    },
    {
        id: "curtsy-lunge",
        name: "Curtsy lunge",
        imageName: "reverse-lunge", // fallback
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Stand tall and step one foot diagonally behind the other. Lower until both knees bend comfortably, keeping your front knee tracking over your toes and chest up. Drive through the front foot to return.",
    },
    {
        id: "db-split-squat",
        name: "Dumbbell split squat",
        imageName: "split-squat", // fallback
        region: "legs",
        equipment: "dumbbells",
        intensity: 3,
        minLevel: 1,
        unit: "reps",
        cue: "Hold dumbbells at your sides in a staggered stance. Keep your torso upright and lower the back knee straight toward the floor. Drive through the front foot to stand. Complete the same reps on both sides.",
    },
    {
        id: "band-glute-bridge",
        name: "Banded glute bridge",
        imageName: "glute-bridge", // fallback
        region: "legs",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Place a band above your knees and lie on your back with feet flat. Press your knees gently outward, drive through your heels, and lift your hips. Squeeze your glutes at the top, then lower slowly.",
    },
    {
        id: "single-leg-calf-raise",
        name: "Single-leg calf raise",
        imageName: "calf-raise", // fallback
        region: "legs",
        equipment: "none",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Stand on one foot with light hand support for balance. Rise as high as possible onto the ball of your foot, pause, then lower your heel for a controlled 3-second descent. Complete both sides.",
    },

    // ---- core
    {
        id: "plank",
        name: "Front plank",
        imageName: "plank",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Place forearms under your shoulders with legs extended. Push the floor away, brace your abs, and gently tuck your tailbone so your body forms a straight line. Keep hips from sagging or rising while breathing normally.",
    },
    {
        id: "side-plank",
        name: "Side plank",
        imageName: "side-plank",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Lie on your side with your elbow under your shoulder and legs stacked. Brace your core and lift your hips until your body forms a straight line. Stack your shoulders and lift the bottom ribs away from the floor.",
    },
    {
        id: "deadbug",
        name: "Dead bug",
        imageName: "dead-bug",
        region: "core",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your back with arms up and knees bent at 90°. Brace your abs and press your lower back into the floor. Slowly extend the opposite arm and leg, then return and alternate without letting your back arch.",
    },
    {
        id: "hollow-hold",
        name: "Hollow hold",
        imageName: "hollow-body-hold",
        region: "core",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Lie on your back and brace your abs to flatten your lower back against the floor. Lift your shoulders and legs slightly. Lower the legs only as far as you can without arching your back, then hold.",
    },
    {
        id: "leg-raise",
        name: "Lying leg raise",
        imageName: "lying-leg-raise",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Lie flat with legs extended and hands beside you or under your hips. Brace your core and raise your legs without swinging. Lower them slowly and stop before your lower back lifts from the floor.",
    },
    {
        id: "bird-dog",
        name: "Bird dog",
        imageName: "bird-dog",
        region: "core",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Start on hands and knees with hands under shoulders and knees under hips. Brace your core and slowly extend the opposite arm and leg. Keep hips level, pause briefly, then return and switch sides.",
    },
    {
        id: "hanging-knee-raise",
        name: "Hanging knee raise",
        imageName: "hanging-knee-raise",
        region: "core",
        equipment: "pullupbar",
        intensity: 3,
        minLevel: 2,
        unit: "reps",
        cue: "Hang from the bar with arms extended and shoulders active. Brace your core, curl your pelvis toward your ribs, and raise your knees without swinging. Lower slowly to the starting position.",
    },
    {
        id: "db-suitcase-hold",
        name: "Suitcase carry hold",
        imageName: "farmer-carry",
        region: "core",
        equipment: "dumbbells",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Stand tall holding one dumbbell at your side. Brace your abs and keep your shoulders and hips level rather than leaning toward the weight. Hold steady while breathing normally, then switch sides.",
    },
    {
        id: "russian-twist",
        name: "Russian twist",
        imageName: "russian-twist",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Sit with knees bent and torso slightly reclined while keeping your spine long. Brace your core and rotate your shoulders from side to side. Move your torso rather than only your hands, keeping the motion controlled.",
    },
    {
        id: "paloff-press",
        name: "Pallof press",
        imageName: "pallof-press",
        region: "core",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band at chest height and stand sideways to the anchor. Hold the band at your chest, brace your core, and press both hands straight forward. Resist the band pulling you into rotation, then return.",
    },
    {
        id: "plank-shoulder-tap",
        name: "Plank shoulder tap",
        imageName: "plank-shoulder-tap",
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Start in a strong high plank with hands under shoulders. Widen your feet for stability and brace your core. Lift one hand to tap the opposite shoulder without shifting your hips, then alternate sides.",
    },
    // new
    {
        id: "reverse-crunch",
        name: "Reverse crunch",
        imageName: "lying-leg-raise", // fallback
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your back with knees bent over your hips. Brace your abs and curl your pelvis toward your ribs, lifting your hips slightly off the floor. Lower slowly without swinging your legs.",
    },
    {
        id: "band-woodchop",
        name: "Band woodchop",
        imageName: "pallof-press", // fallback
        region: "core",
        equipment: "bands",
        intensity: 2,
        minLevel: 0,
        unit: "reps",
        cue: "Anchor the band high to one side and hold it with both hands. Brace your core and pull diagonally down across your body, rotating through your torso and pivoting the back foot. Return slowly. Complete both sides.",
    },
    {
        id: "plank-reach",
        name: "Plank reach",
        imageName: "plank-shoulder-tap", // fallback
        region: "core",
        equipment: "none",
        intensity: 2,
        minLevel: 1,
        unit: "reps",
        cue: "Start in a high plank with feet wide. Brace your core and reach one arm straight forward without letting your hips rotate. Return the hand to the floor and alternate sides.",
    },
    {
        id: "high-plank-hold",
        name: "High plank hold",
        imageName: "plank", // fallback
        region: "core",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Place hands under your shoulders with arms straight and legs extended. Push the floor away, brace your abs, and keep your body in one line from head to heels. Breathe steadily throughout.",
    },

    // ---- mobility
    {
        id: "worlds-greatest",
        name: "World's greatest stretch",
        imageName: "worlds-greatest-stretch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Step into a deep lunge with both hands near the front foot. Keep the back leg long or lowered, rotate the front arm upward, and follow it with your eyes. Breathe out gently at the end range, then switch sides.",
    },
    {
        id: "cat-cow",
        name: "Cat-cow",
        imageName: "cat-cow-stretch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Start on hands and knees with wrists under shoulders. Slowly round your spine by tucking your tailbone and chin, then reverse by lifting your chest and tailbone. Move smoothly through each vertebra without forcing range.",
    },
    {
        id: "hip-90-90",
        name: "90/90 hip switch",
        imageName: "kneeling-hip-flexor-stretch", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Sit with both knees bent and legs positioned in a 90/90 shape. Keep your chest tall and rotate both knees from one side to the other without using your hands. Move slowly and stay controlled throughout.",
    },
    {
        id: "thoracic-rotation",
        name: "Open book rotation",
        imageName: "worlds-greatest-stretch", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Lie on your side with knees bent and arms extended in front. Keep your knees together while opening the top arm across your body toward the floor behind you. Follow the hand with your eyes, then return.",
    },
    {
        id: "couch-stretch",
        name: "Couch stretch",
        imageName: "kneeling-hip-flexor-stretch",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Place one shin or foot against a wall or couch behind you and step the other foot forward. Brace your core and gently tuck your pelvis before leaning back. Keep the stretch controlled and avoid excessive lower-back arching.",
    },
    {
        id: "deep-squat-hold",
        name: "Deep squat hold",
        imageName: "bodyweight-squat", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Take a comfortable wide stance and sink into a deep squat. Keep your heels down if your mobility allows, use your elbows to gently guide the knees outward, and keep your chest lifted while breathing slowly.",
    },
    {
        id: "shoulder-dislocate",
        name: "Band shoulder pass-through",
        imageName: "reverse-snow-angel", // fallback
        region: "mobility",
        equipment: "bands",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Hold a band with a wide grip in front of you. Keep elbows straight and slowly sweep the band overhead and behind you, then return. Use a grip wide enough to move comfortably and avoid shrugging.",
    },
    {
        id: "ankle-rock",
        name: "Half-kneel ankle rock",
        imageName: "bodyweight-squat", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Kneel with one foot planted ahead and keep its heel firmly down. Slowly drive the front knee forward over the toes without collapsing inward. Return smoothly and repeat, exploring the ankle's comfortable range.",
    },
    {
        id: "thread-the-needle",
        name: "Thread the needle",
        imageName: "cat-cow-stretch", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Start on hands and knees. Slide one arm underneath your body with the palm facing up, rotating your upper back until the shoulder rests gently on the floor. Pause, then return and repeat on the other side.",
    },
    {
        id: "frog-stretch",
        name: "Frog stretch",
        imageName: "cossack-squat", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Start on hands and knees, then move your knees wide with ankles roughly in line with them. Keep your back comfortable and gently rock your hips backward until you feel a controlled inner-thigh stretch.",
    },
    {
        id: "scapular-pushup",
        name: "Scapular push-up",
        imageName: "scapular-push-up",
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Start in a plank with arms completely straight. Without bending your elbows, let your chest sink slightly as the shoulder blades move together. Then push the floor away to spread the shoulder blades. Keep your body stable.",
    },
    // new
    {
        id: "hip-flexor-lunge",
        name: "Low lunge hip stretch",
        imageName: "kneeling-hip-flexor-stretch", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Step into a low lunge with the back knee on the floor. Tuck your pelvis gently and shift your hips forward until you feel a stretch at the front of the back hip. Keep your chest tall and breathe slowly.",
    },
    {
        id: "quadruped-rockback",
        name: "Quadruped rock-back",
        imageName: "cat-cow-stretch", // fallback
        region: "mobility",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "reps",
        cue: "Start on hands and knees with a neutral spine. Slowly rock your hips back toward your heels while keeping your back flat. Pause when you feel a comfortable stretch, then return to the start.",
    },

    // ---- cardio / conditioning
    {
        id: "jump-rope",
        name: "Rope skips (or mimic)",
        imageName: "jump-rope",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Hold a jump rope or mimic the motion without one. Make small, quick hops from the balls of your feet and keep your knees slightly bent. Land softly and maintain a steady rhythm rather than jumping high.",
    },
    {
        id: "mountain-climber",
        name: "Mountain climber",
        imageName: "mountain-climber",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Start in a strong high plank with hands under shoulders. Brace your core and drive one knee toward your chest, then switch legs quickly. Keep your hips relatively low and avoid bouncing or excessively rotating your body.",
    },
    {
        id: "step-up",
        name: "Fast step-up",
        imageName: "step-up",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Use a stable step or platform. Place your whole foot on it, drive through that leg and extend the hip to stand tall, then step down under control. Alternate legs while maintaining a quick, steady rhythm.",
    },
    {
        id: "burpee",
        name: "Burpee",
        imageName: "burpee",
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "From standing, squat down and place your hands on the floor. Step or jump your feet back into a plank, lower your chest toward the floor, then return your feet under you. Stand tall and repeat at a controlled pace.",
    },
    {
        id: "shadow-box",
        name: "Shadow boxing",
        imageName: "high-knees", // fallback
        region: "cardio",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Stand in a light athletic stance with knees soft and feet active. Throw controlled punches while moving around. Rotate through the hips and shoulders, return hands to guard, and breathe out with each punch.",
    },
    {
        id: "squat-jump",
        name: "Squat jump",
        imageName: "jump-squat",
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Start in a comfortable squat with your chest lifted. Drive through your feet to jump vertically, then land softly with bent knees and absorb the impact into another squat. Keep landings quiet and controlled.",
    },
    {
        id: "high-knees",
        name: "High knees",
        imageName: "high-knees",
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Stand tall and run in place while driving each knee toward hip height. Stay light on the balls of your feet, keep your torso upright, and pump your arms naturally. Maintain a quick rhythm without losing control.",
    },
    {
        id: "skater-jumps",
        name: "Skater jumps",
        imageName: "skater-hop",
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Start on one leg and leap laterally to the opposite side. Land softly on the other leg with the knee bent and hips back, then immediately push sideways again. Use your arms for balance and control each landing.",
    },
    {
        id: "jumping-jacks",
        name: "Jumping jacks",
        imageName: "jump-rope", // fallback
        region: "cardio",
        equipment: "none",
        intensity: 1,
        minLevel: 0,
        unit: "seconds",
        cue: "Stand tall with feet together and arms at your sides. Jump your feet out while raising your arms overhead, then jump back to the starting position. Stay light on your feet and use a comfortable, steady rhythm.",
    },
    // new
    {
        id: "butt-kicks",
        name: "Butt kicks",
        imageName: "high-knees", // fallback
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Jog in place while flicking your heels up toward your glutes. Stay tall, keep your knees pointing down, and stay light on the balls of your feet. Pump your arms and keep a quick, steady rhythm.",
    },
    {
        id: "lateral-shuffle",
        name: "Lateral shuffle",
        imageName: "skater-hop", // fallback
        region: "cardio",
        equipment: "none",
        intensity: 2,
        minLevel: 0,
        unit: "seconds",
        cue: "Sink into a slight athletic squat with chest up. Shuffle sideways in quick steps without crossing your feet, then reverse direction. Stay low and light on your feet throughout.",
    },
    {
        id: "plank-jack",
        name: "Plank jack",
        imageName: "jump-rope", // fallback
        region: "cardio",
        equipment: "none",
        intensity: 3,
        minLevel: 1,
        unit: "seconds",
        cue: "Start in a high plank with hands under shoulders. Brace your core and jump your feet wide, then back together, like a horizontal jumping jack. Keep your hips level and land softly.",
    },
];

/**
 * A map from exercise IDs to their corresponding exercises.
 */
export const EXERCISE_BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));


/**
 * Dev-time check. Pass the slugs that actually exist in your animation
 * library to catch any imageName that doesn't resolve, plus duplicate ids.
 */
export function validateExercises(availableImageNames?: Set<string>): void {
    const seen = new Set<string>();
    for (const e of EXERCISES) {
        if (seen.has(e.id)) console.warn("Duplicate exercise id:", e.id);
        seen.add(e.id);
    }
    if (availableImageNames) {
        const broken = EXERCISES.filter((e) => !availableImageNames.has(e.imageName)).map(
            (e) => `${e.id} -> ${e.imageName}`,
        );
        if (broken.length) console.warn("imageName not found:", broken);
    }
}
